import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'hi_IN': {
          'setting': 'सेटिंग',
          'agra': 'आगरा',
          'varansi': 'वाराणसी',
          'language': 'भाषा',
          'home': 'होम',
          'bookmark': 'बुकमार्क',
          'location': 'जगह',
          'profile': 'प्रोफ़ाइल',
          'national': 'राष्ट्रीय',
          'international': 'अंतरराष्ट्रीय',
          'state': 'राज्य',
          'theme': 'रोशनी / अँधेरा',
          'e_paper': 'ई पेपर',
          'support': 'सहायता',
          'about_us': 'हमारे बारे मे',
          'email_support': 'ई - मेल समर्थन',
          'account': 'अकाउंट',
          'loginLogout': 'लॉग इन / लॉग आउट',
          'phoneNumber': 'फ़ोन नंबर',
          'email': 'ई-मेल',
          'password': 'पासवर्ड',
          'login': 'लॉग इन',
          'logout': 'लॉग आउट',
          'notificationSetting': 'सूचना सेटिंग',
          'new_user': 'नए उपयोगकर्ता? ',
          'create_account': 'अकाउंट बनाएं',
          'first_name': 'नाम',
          'last_name': 'उपनाम',
          'reporter': 'रिपोर्टर',
          'user': 'उपयोगकर्ता',
          'signup': 'खाता बनाएं',
          'search': 'खोज',
          'notificatios': 'सूचनाएं',
          'edit_profile': 'प्रोफ़ाइल संपादित करें',
          'upload_news': 'समाचार अपलोड करें',
          'heading': 'शीर्षक',
          'sub_heading': 'उपशीर्षक',
          'description ': 'विवरण',
          'photo ': 'तस्वीर',
          'upload ': 'अपलोड करे',
          'photo': 'तस्वीर',
          'message': 'संदेश',
          'camera': 'कैमरा',
          'gallery': 'गेलरी',
          'cancel': 'रद्द',
          'enter_password': 'कृपया पासवर्ड दर्ज करें',
          'enter_first_name': 'कृपया प्रथम नाम दर्ज करें',
          'enter_last_name': 'कृपया अंतिम नाम दर्ज करें',
          'loading': 'लोड हो रहा है...',
          'no_news_available': 'कोई समाचार उपलब्ध नहीं है',
        },
        'en_US': {
          'setting': 'SETTING',
          'varansi': 'Varansi',
          'agra': 'Agra',
          'language': 'Language',
          'home': 'Home',
          'bookmark': 'Bookmark',
          'location': 'Location',
          'profile': 'Profile',
          'national': 'National',
          'international': 'International',
          'state': 'State',
          'theme': 'Light / Dark',
          'e_paper': 'E-Paper',
          'support': 'SUPPORT',
          'about_us': 'About us',
          'email_support': 'Email support',
          'account': 'Account',
          'loginLogout': 'Login / Logout',
          'email': 'Email',
          'password': 'Password',
          'login': 'Login',
          'logout': 'Logout',
          'notificationSetting': 'Notification Setting',
          'new_user': 'New user? ',
          'create_account': 'create account',
          'first_name': 'First Name',
          'last_name': 'Last Name',
          'reporter': 'Reporter',
          'user': 'User',
          'signup': 'Signup',
          'search': 'Search',
          'notificatios': 'Notifications',
          'edit_profile': 'Edit Profile',
          'upload_news': 'Upload News',
          'heading': 'Heading',
          'sub_heading': 'Sub Heading',
          'description ': 'Description',
          'photo ': 'Photo',
          'upload ': 'Upload',
          'photo': 'Photo',
          'message': 'Message',
          'camera': 'CAMERA',
          'gallery': 'GALLERY',
          'cancel': 'CANCEL',
          'enter_password': 'Please enter password',
          'enter_first_name': 'Please enter First Name',
          'enter_last_name': 'Please enter Last Name',
          'phoneNumber': 'Mobile Number',
          'loading': 'Loading...',
          'no_news_available': 'No news avaiable',
        },
      };
}
