import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'hi_IN': {
          'setting': 'सेटिंग',
          'agra': 'आगरा',
          'varansi': 'वाराणसी',
          'language': 'भाषा',
          'home': 'होम',
          'bookmark': 'बुकमार्क',
          'location': 'जगह',
          'profile': 'प्रोफ़ाइल',
          'national': 'राष्ट्रीय',
          'international': 'अंतरराष्ट्रीय',
          'state': 'राज्य',
          'theme': 'रोशनी / अँधेरा',
          'e_paper': 'ई पेपर',
          'support': 'सहायता',
          'about_us': 'हमारे बारे मे',
          'email_support': 'ई - मेल समर्थन',
          'account': 'अकाउंट',
          'loginLogout': 'लॉग इन',
          'phoneNumber': 'फ़ोन नंबर',
          'email': 'ई-मेल',
          'password': 'पासवर्ड',
          'login': 'लॉग इन',
          'logout': 'लॉग आउट',
          'notificationSetting': 'सूचना सेटिंग',
          'new_user': 'नए उपयोगकर्ता? ',
          'create_account': 'अकाउंट बनाएं',
          'first_name': 'नाम',
          'last_name': 'उपनाम',
          'reporter': 'रिपोर्टर',
          'reader': 'पाठक',
          'signup': 'खाता बनाएं',
          'search': 'खोज',
          'notificatios': 'सूचनाएं',
          'edit_profile': 'प्रोफ़ाइल संपादित करें',
          'upload_news': 'समाचार अपलोड करें',
          'heading': 'शीर्षक',
          'sub_heading': 'उपशीर्षक',
          'description ': 'विवरण',
          'photo ': 'तस्वीर',
          'upload ': 'अपलोड करे',
          'photo': 'तस्वीर',
          'message': 'संदेश',
          'camera': 'कैमरा',
          'gallery': 'गेलरी',
          'cancel': 'रद्द',
          'enter_password': 'कृपया पासवर्ड दर्ज करें',
          'enter_first_name': 'कृपया प्रथम नाम दर्ज करें',
          'enter_last_name': 'कृपया अंतिम नाम दर्ज करें',
          'loading': 'लोड हो रहा है...',
          'no_news_available': 'कोई समाचार उपलब्ध नहीं है',
          'news_details': 'समाचार विवरण',
          'please_select_location': 'कृपया स्थान चुनें',
          'please_select_category': 'कृपया श्रेणी चुनें',
          'please_select_heading': 'कृपया शीर्षक दर्ज करें',
          'please_select_subheading': 'कृपया उपशीर्षक दर्ज करें',
          'please_select_description': 'कृपया विवरण दर्ज करें',
          'upload_image': 'तश्वीरें अपलोड करें',
          'in_minutes': 'मिनट पढ़े',
          'please_enter_valid_search_key': 'कृपया वैध खोज कुंजी दर्ज करें',
          'search_messgae': 'स्क्रीन के शीर्ष पर, अपने खोज शब्द को टाइप करें।',
          'search_here': 'यहाँ खोजें...',
          'forgot_password': 'पासवर्ड भूल गए?',
          'please_enter_valid_email': 'कृपया वैध ईमेल दर्ज करें।',
          'send': 'भेजें',
          'something_went_wrong': '"कुछ गलत हो गया"',
          'error': 'त्रुटि हुई',
          'logout_message': 'क्या आप लॉगआउट करना चाहते हैं?',
          'no': 'नहीं',
          'yes': 'हां',
          'mobileNumber': 'मोबाइल नंबर',
          'unauthorized_title': 'अनधिकृत पहुँच',
          'unauthorized_message':
              'आपके खाते की इस पृष्ठ तक पहुँच नहीं है। कृपया अपने खाते में लॉगिन करें।',
          'ok': 'ठीक है।',
          'success': 'सफलता',
          'registration_success_alert': "खाता सफलतापूर्वक बनाया गया है",
          'news_created_successfully': 'समाचार सफलतापूर्वक बनाया गया!',
          'change_password': 'पासवर्ड बदलें',
          'confirm_password': 'पासवर्ड पुष्टि करें',
          'new_password': 'नया पासवर्ड',
          'password_change_success_message': 'पासवर्ड सफलतापूर्वक बदल गया!',
          'no_internet_title': 'कोई इंटरनेट कनेक्शन नहीं है।',
          'app_version': 'ऐप संस्करण: ',
          'breaking_news': 'ब्रेकिंग',
          'no_internet_message':
              'इस क्षेत्र में उपलब्ध विशेषता इंटरनेट कनेक्टिविटी की आवश्यकता है। कृपया अपने डिवाइस को इंटरनेट से कनेक्ट करें और पुनः प्रयास करें।',
          'editorial_news': 'संपादकीय'
        },
        'en_US': {
          'setting': 'SETTING',
          'varansi': 'Varansi',
          'agra': 'Agra',
          'language': 'Language',
          'home': 'Home',
          'bookmark': 'Bookmark',
          'location': 'Location',
          'profile': 'Profile',
          'national': 'National',
          'international': 'International',
          'state': 'State',
          'theme': 'Light / Dark',
          'e_paper': 'E-Paper',
          'support': 'SUPPORT',
          'about_us': 'About us',
          'email_support': 'Email support',
          'account': 'Account',
          'loginLogout': 'Login',
          'email': 'Email',
          'password': 'Password',
          'login': 'Login',
          'logout': 'Logout',
          'notificationSetting': 'Notification Setting',
          'new_user': 'New user? ',
          'create_account': 'create account',
          'first_name': 'First Name',
          'last_name': 'Last Name',
          'reporter': 'Reporter',
          'reader': 'Reader',
          'signup': 'Signup',
          'search': 'Search',
          'notificatios': 'Notifications',
          'edit_profile': 'Edit Profile',
          'upload_news': 'Upload News',
          'heading': 'Heading',
          'sub_heading': 'Sub Heading',
          'description ': 'Description',
          'photo ': 'Photo',
          'upload ': 'Upload',
          'photo': 'Photo',
          'message': 'Message',
          'camera': 'CAMERA',
          'gallery': 'GALLERY',
          'cancel': 'CANCEL',
          'enter_password': 'Please enter password',
          'enter_first_name': 'Please enter First Name',
          'enter_last_name': 'Please enter Last Name',
          'phoneNumber': 'Mobile Number',
          'loading': 'Loading...',
          'no_news_available': 'No news avaiable',
          'news_details': 'News Details',
          'please_select_location': 'Please select location',
          'please_select_category': 'Please select category',
          'please_select_heading': 'Please enter heading',
          'please_select_subheading': 'Please enter sub heading',
          'please_select_description': 'Please enter description',
          'upload_image': 'Upload images',
          'in_minutes': 'mins read',
          'please_enter_valid_search_key': 'Please enter valid search key',
          'search_messgae': 'At the top of the screen, type your search word.',
          'search_here': 'Search here...',
          'forgot_password': 'Forgot password?',
          'please_enter_valid_email': 'Please enter valid email',
          'send': 'Send',
          'something_went_wrong': 'Something went wrong.',
          'error': 'Error',
          'no': 'NO',
          'yes': 'YES',
          'mobileNumber': 'Mobile Number',
          'unauthorized_title': 'Unauthorized Access',
          'unauthorized_message':
              'Your account does not have access to this page. Please login your account.',
          'ok': 'OK',
          'success': 'Success',
          'registration_success_alert':
              "Account has been created successfully!",
          'news_created_successfully': 'News created successfully!',
          'change_password': 'Change password',
          'confirm_password': 'Confirm password',
          'new_password': 'New password',
          'password_change_success_message': 'Password changed successfully!',
          'no_internet_title': 'No internet connection.',
          'app_version': 'App Version: ',
          'breaking_news': 'Breaking',
          'editorial_news': 'Editorial',
          'no_internet_message':
              'The feature in this area require internet connectivity. Please connect your device to the internet and try again.'
        },
      };
}
